name: 'Anka Actions'
description: "Stub: Don't use this action directly. Read [the documentation](https://github.com/veertuinc/anka-actions) instead."
author: 'Veertu Inc.'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: 'Stub'
      run: |
        echo 'This is a stub. Read [the documentation](https://github.com/veertuinc/anka-actions) instead.'
        exit 1
      shell: bash